/-
SPDX-License-Identifier: Apache-2.0
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
module

public import AlgebraicDirectLimits.CofinalGroupCompletion
public import Mathlib.Algebra.Group.Subgroup.Ker
public import Mathlib.Algebra.Group.Submonoid.Membership
public import Mathlib.CategoryTheory.Types.Basic
public import Mathlib.Order.DirectedInverseSystem
import Mathlib.Tactic.Abel

/-!
# Graded stabilization and the kernel of group completion

Let `d : M →+ A` be a homomorphism of additive commutative monoids and `u : M`.
The degree fibers `d m = n • d u` form a natural-indexed directed system whose
transition maps add copies of `u`. Their native set-valued direct limit maps to
the kernel of the homomorphism induced by `d` on Grothendieck additive groups,
sending a representative `(n, m)` to `of m - n • of u`.

If the cyclic submonoid generated by `u` has top saturation, this normalization
is injective. Equality is characterized by eventual cyclic stabilization; no
cancellation in either monoid or injectivity of the stage maps is needed.
When the degree target `A` is cancellative, normalization is also surjective
and yields `normalizationEquiv`. The monoids may lie in independent universes.

The equivalence is an equivalence of types. No additive structure on the
degree-fiber direct limit or additive equivalence is asserted here.
-/

public section

namespace Algebra.GrothendieckAddGroup.GradedStabilization

open Algebra Algebra.GrothendieckAddGroup

universe uM uA

variable {M : Type uM} [AddCommMonoid M] {A : Type uA} [AddCommMonoid A]

/-- A natural-indexed fiber of the degree map; it is not a stagewise group. -/
@[expose] def degreeFiber (d : M →+ A) (u : M) (n : ℕ) := {m : M // d m = n • d u}

/-- Stabilization by the missing natural number of copies of `u`. -/
@[expose] def transition (d : M →+ A) (u : M) (n k : ℕ) (h : n ≤ k) :
    TypeCat.Fun (degreeFiber d u n) (degreeFiber d u k) :=
  ⟨fun m => ⟨m.1 + (k - n) • u, by
    rw [map_add, map_nsmul, m.2, ← add_nsmul]
    congr 1
    omega⟩⟩

/-- The degree fibers and stabilization maps form a native directed system. -/
instance degreeDirectedSystem (d : M →+ A) (u : M) :
    DirectedSystem (degreeFiber d u) (transition d u · · ·) where
  map_self := by
    intro n m
    apply Subtype.ext
    change m.1 + (n - n) • u = m.1
    simp
  map_map := by
    intro k j n hnj hjk m
    apply Subtype.ext
    change (m.1 + (j - n) • u) + (k - j) • u = m.1 + (k - n) • u
    rw [add_assoc, ← add_nsmul]
    congr 2
    omega

/-- The native completion homomorphism induced by degree. -/
@[expose] noncomputable def inducedDegree (d : M →+ A) :
    GrothendieckAddGroup M →+ GrothendieckAddGroup A :=
  lift ((of (M := A)).comp d)

/-- The induced degree homomorphism sends a canonical image to its degree image. -/
theorem inducedDegree_of (d : M →+ A) (m : M) :
    inducedDegree d (of m) = of (d m) := by
  have h := (lift (M := M) (G := GrothendieckAddGroup A)).symm_apply_apply
    ((of (M := A)).comp d)
  exact congrArg (fun f : M →+ GrothendieckAddGroup A => f m) h

/-- The induced degree computation in the native localization simp normal form. -/
@[simp] theorem inducedDegree_addMonoidOf (d : M →+ A) (m : M) :
    inducedDegree d (AddLocalization.addMonoidOf ⊤ m) =
      AddLocalization.addMonoidOf ⊤ (d m) :=
  inducedDegree_of d m

/-- A degree-fiber representative determines an element of the actual kernel. -/
@[expose] noncomputable def normalizedAt (d : M →+ A) (u : M) (n : ℕ)
    (m : degreeFiber d u n) : (inducedDegree d).ker :=
  ⟨of m.1 - n • of u, by
    change inducedDegree d (of m.1 - n • of u) = 0
    rw [map_sub, map_nsmul, inducedDegree_of, inducedDegree_of, m.2, map_nsmul,
      sub_self]⟩

/-- Stabilization preserves the normalized element of the completion kernel. -/
theorem normalizedAt_transition (d : M →+ A) (u : M) (n k : ℕ) (h : n ≤ k)
    (m : degreeFiber d u n) :
    normalizedAt d u n m = normalizedAt d u k (transition d u n k h m) := by
  apply Subtype.ext
  change of m.1 - n • of u = of (m.1 + (k - n) • u) - k • of u
  rw [map_add, map_nsmul]
  have hk : k • of u = n • of u + (k - n) • of u := by
    rw [← add_nsmul]
    congr 1
    omega
  rw [hk]
  abel

/-- The descended normalized map, using the native set-valued direct limit. -/
@[expose] noncomputable def normalization (d : M →+ A) (u : M) :
    DirectLimit (degreeFiber d u) (transition d u) → (inducedDegree d).ker :=
  DirectLimit.lift (transition d u) (normalizedAt d u)
    (normalizedAt_transition d u)

/-- Normalization on a direct-limit representative is the specified difference. -/
@[simp] theorem normalization_mk (d : M →+ A) (u : M) (n : ℕ)
    (m : degreeFiber d u n) :
    (normalization d u ⟦⟨n, m⟩⟧).1 = of m.1 - n • of u := rfl

/-- A cofinal cyclic submonoid supplies all normalized group representatives. -/
theorem exists_normalized_representative (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) (z : GrothendieckAddGroup M) :
    ∃ (m : M) (n : ℕ), z = of m - n • of u := by
  obtain ⟨m, l, hl⟩ := exists_cofinal_denominator (AddSubmonoid.multiples u) hu z
  obtain ⟨n, hn⟩ := l.property
  refine ⟨m, n, ?_⟩
  simpa only [← hn, map_nsmul] using hl

/-- Equality of canonical images is stabilization by copies of the same `u`. -/
theorem of_eq_iff_cyclic_stabilizer (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) (x y : M) :
    of x = of y ↔ ∃ ell : ℕ, x + ell • u = y + ell • u := by
  constructor
  · intro h
    obtain ⟨l, hl⟩ :=
      (of_eq_iff_exists_cofinal_stabilizer (AddSubmonoid.multiples u) hu x y).mp h
    obtain ⟨ell, hell⟩ := l.property
    exact ⟨ell, by simpa only [hell] using hl⟩
  · rintro ⟨ell, hell⟩
    have h := congrArg (of (M := M)) hell
    simpa only [map_add, add_left_inj] using h

/-- Normalized equality is precisely equality after one common cyclic stabilization. -/
theorem normalized_eq_iff (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) (n n' : ℕ) (m m' : M) :
    of m - n • of u = of m' - n' • of u ↔
      ∃ ell : ℕ, m + (n' + ell) • u = m' + (n + ell) • u := by
  rw [sub_eq_sub_iff_add_eq_add]
  have hcross : of m + n' • of u = of m' + n • of u ↔
      of (m + n' • u) = of (m' + n • u) := by
    simp only [map_add, map_nsmul]
  rw [hcross, of_eq_iff_cyclic_stabilizer u hu]
  simp only [add_nsmul, add_assoc]

/-- Injectivity comes from eventual equality, not injective stage maps. -/
theorem normalization_injective (d : M →+ A) (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) :
    Function.Injective (normalization d u) := by
  intro x y hxy
  obtain ⟨n, m, rfl⟩ := DirectLimit.exists_eq_mk (transition d u) x
  obtain ⟨n', m', rfl⟩ := DirectLimit.exists_eq_mk (transition d u) y
  have h := congrArg Subtype.val hxy
  change of m.1 - n • of u = of m'.1 - n' • of u at h
  obtain ⟨ell, hell⟩ := (normalized_eq_iff u hu n n' m.1 m'.1).mp h
  apply Quotient.sound
  refine ⟨n + n' + ell, by change n ≤ _; omega, by change n' ≤ _; omega, ?_⟩
  apply Subtype.ext
  change m.1 + (n + n' + ell - n) • u = m'.1 + (n + n' + ell - n') • u
  simpa only [show n + n' + ell - n = n' + ell by omega,
    show n + n' + ell - n' = n + ell by omega] using hell

/-- The actual direct-limit equality relation is cyclic eventual equality. -/
theorem mk_eq_iff (d : M →+ A) (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) (n n' : ℕ)
    (m : degreeFiber d u n) (m' : degreeFiber d u n') :
    (⟦⟨n, m⟩⟧ : DirectLimit (degreeFiber d u) (transition d u)) = ⟦⟨n', m'⟩⟧ ↔
      ∃ ell : ℕ, m.1 + (n' + ell) • u = m'.1 + (n + ell) • u := by
  rw [← (normalization_injective d u hu).eq_iff, Subtype.ext_iff]
  exact normalized_eq_iff u hu n n' m.1 m'.1

/-- Same-stage representatives need only become equal after stabilization. -/
theorem mk_same_stage_eq_iff (d : M →+ A) (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) (n : ℕ)
    (m m' : degreeFiber d u n) :
    (⟦⟨n, m⟩⟧ : DirectLimit (degreeFiber d u) (transition d u)) = ⟦⟨n, m'⟩⟧ ↔
      ∃ ell : ℕ, m.1 + ell • u = m'.1 + ell • u := by
  rw [← (normalization_injective d u hu).eq_iff, Subtype.ext_iff]
  change of m.1 - n • of u = of m'.1 - n • of u ↔ _
  rw [sub_left_inj]
  exact of_eq_iff_cyclic_stabilizer u hu m.1 m'.1

/-- Target cancellation recovers the exact degree-fiber condition. -/
theorem normalization_surjective [IsCancelAdd A] (d : M →+ A) (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) :
    Function.Surjective (normalization d u) := by
  intro z
  obtain ⟨m, n, hn⟩ := exists_normalized_representative u hu z.1
  have hz : inducedDegree d (of m - n • of u) = 0 := by
    rw [← hn]
    exact z.property
  rw [map_sub, map_nsmul, inducedDegree_of, inducedDegree_of, sub_eq_zero] at hz
  have hm : d m = n • d u := of_injective (by simpa only [map_nsmul] using hz)
  refine ⟨⟦⟨n, ⟨m, hm⟩⟩⟧, ?_⟩
  apply Subtype.ext
  exact hn.symm

/-- The native direct limit is equivalent to the native completion kernel. -/
@[expose] noncomputable def normalizationEquiv [IsCancelAdd A] (d : M →+ A) (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) :
    DirectLimit (degreeFiber d u) (transition d u) ≃ (inducedDegree d).ker :=
  Equiv.ofBijective (normalization d u)
    ⟨normalization_injective d u hu, normalization_surjective d u hu⟩

/-- The equivalence retains the explicit normalization formula on representatives. -/
@[simp] theorem normalizationEquiv_mk [IsCancelAdd A] (d : M →+ A) (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) (n : ℕ)
    (m : degreeFiber d u n) :
    (normalizationEquiv d u hu ⟦⟨n, m⟩⟧).1 = of m.1 - n • of u := rfl

/-- The choice-defined inverse returns every specified valid representative. -/
theorem normalizationEquiv_symm_eq_mk [IsCancelAdd A] (d : M →+ A) (u : M)
    (hu : (AddSubmonoid.multiples u).saturation = ⊤) (z : (inducedDegree d).ker)
    (n : ℕ) (m : degreeFiber d u n) (hz : z.1 = of m.1 - n • of u) :
    (normalizationEquiv d u hu).symm z = ⟦⟨n, m⟩⟧ := by
  apply (normalizationEquiv d u hu).injective
  rw [Equiv.apply_symm_apply]
  exact Subtype.ext hz

end Algebra.GrothendieckAddGroup.GradedStabilization
